name: Python CI

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Set the OS to Ubuntu for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.9'  # Use Python 3.9, can change to another version like 3.8 or 3.7 if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests with Pytest
        run: |
          pytest  # Run your tests using Pytest

      - name: Upload test results as an artifact (optional)
        uses: actions/upload-artifact@v3  # Use the updated v3 version
        with:
          name: test-results
          path: results/  # Adjust this path to where your test results are saved, if necessary
